### ISSUE TITLE
onSemanticTokens e.startsWith is not a function error from vscode 'ansible server' output

### ISSUE THREAD

**Issue by piengeng** [ansible/ansible-language-server#473]
```
[Error - 9:48:54 am] An error occurred in 'onSemanticTokens' handler: [TypeError] e.startsWith is not a function
TypeError: e.startsWith is not a function
    at t.isTaskKeyword (/home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:102619)
    at /home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:124711
    at Array.filter (<anonymous>)
    at /home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:124676
    at Generator.next (<anonymous>)
    at /home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:120967
    at new Promise (<anonymous>)
    at r (/home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:120712)
    at b (/home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:124568)
    at /home/henry/.vscode/extensions/redhat.ansible-1.0.90/out/server/src/server.js:2:40175
```

**Comment by ssbarnea** [comment]
@priyamsahoo @ajinkyau Any ideas?

**Comment by priyamsahoo** [comment]
@piengeng, could you please confirm if ansible is installed in the environment or not?

**Comment by piengeng** [comment]
Ansible was installed with apt on ubuntu jammy, so, not environment.
I'll close this as it's an edge & weird case, Terribly sorry to waste people time on this, as I'm not seeing this anymore, when it happened last time vscode was behaving strangely as well. Thanks for following up.
